export const SUPPORT_CONTACT_ATTACHMENT_MAX_COUNT = 3;
export const SUPPORT_CONTACT_ATTACHMENT_MAX_FILE_SIZE = 1 * 1024 * 1024;
export const SUPPORT_CONTACT_ATTACHMENT_MAX_TOTAL_SIZE = 3 * 1024 * 1024;

export const SUPPORT_CONTACT_IMAGE_COMPRESSION_MAX_SIZE_MB = 0.9;
export const SUPPORT_CONTACT_IMAGE_COMPRESSION_MAX_DIMENSION = 1920;
